/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOWIMPSPEC_CTSPERKEVKGDAYPB
#define ROOWIMPSPEC_CTSPERKEVKGDAYPB

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooWimpSpec_ctsPerkeVkgdaypb : public RooAbsPdf {
public:
  RooWimpSpec_ctsPerkeVkgdaypb() {} ; 
  RooWimpSpec_ctsPerkeVkgdaypb(const char *name, const char *title,
	      RooAbsReal& _Enr,
	      RooAbsReal& _mWimp,
	      RooAbsReal& _targetA,
	      RooAbsReal& _targetZ,
	      RooAbsReal& _rho,
	      //RooAbsReal& _halo_beta,
	      RooAbsReal& _dayOfYear,
	      RooAbsReal& _vEsc,
	      RooAbsReal& _v0,
	      RooAbsReal& _ff_c,
	      RooAbsReal& _ff_a,
	      RooAbsReal& _ff_s,
	      RooAbsReal& _idm_delta);
  RooWimpSpec_ctsPerkeVkgdaypb(const RooWimpSpec_ctsPerkeVkgdaypb& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooWimpSpec_ctsPerkeVkgdaypb(*this,newname); }
  inline virtual ~RooWimpSpec_ctsPerkeVkgdaypb() { }

protected:

  RooRealProxy Enr ;
  RooRealProxy mWimp ;
  RooRealProxy targetA ;
  RooRealProxy targetZ ;
  RooRealProxy rho ;
  //RooRealProxy halo_beta ;
  RooRealProxy dayOfYear ;
  RooRealProxy vEsc ;
  RooRealProxy v0 ;
  RooRealProxy ff_c ;
  RooRealProxy ff_a ;
  RooRealProxy ff_s ;
  RooRealProxy idm_delta ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooWimpSpec_ctsPerkeVkgdaypb,1) // Your description goes here...
};
 
#endif
