%function [output_string] = string_replacement_table(input_string)
%
%String_replacement_table is a simple function that searches a string for
%characters that may cause problems from one system to another.  It then
%replaces these using a table and returns an output string where problem
%characters have been removed.
%--------------------------------------------------------------------------

function [output_string] = String_Replacement_Table(input_string)

output_string = input_string;

string_replacement_table = { ...
      '''', '_apice_'; ...
      ' ', '_spazio_'; ...
      '\', '_slash_'; ...
      '"', '_virgo_'; ...
      '#', '_canc_'; ...
      '%', '_perc_'; ...
      '&', '_and_'; ...
      '*', '_star_'; ...
      '=', '_equals_'; ...
      '.', '_period_'; ...
      ',','_comma_'; ...
      sprintf('\n'),'_pck_'};
 
  for n=1:length(string_replacement_table)
      output_string = strrep(output_string,string_replacement_table{n,1},string_replacement_table{n,2});
  end
  
  return
